# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "https://elsaetantoine.be"
languageCode = "fr"

theme = "congo"
defaultContentLanguage = "fr"

enableRobotsTXT = true
paginate = 15
summaryLength = 0

googleAnalytics = "G-248HJC8VNE"

[outputs]
  home = ["HTML", "RSS", "JSON"]
