languageCode = "fr"
languageName = "Français"
weight = 1

title = "E & A :ring:"
copyright = "&copy; 2023. Fait avec :white_heart: par Elsa & Antoine"

[params]
  isoCode = "fr"
  displayName = ":flag-fr:"
  rtl = false
  
  dateFormat = "2 January 2006"
  description = "Site web reprenant toutes les informations concernant le mariage d'Elsa et Antoine"

[author]
  name = " "
  # image = "img/author.jpg"
  # headline = ""
  # bio = "Site web pour le mariage d'Elsa et Antoine"
#   links = [
   # { twitter = "https://twitter.com/" },
   # { facebook = "https://facebook.com/" },
   # { linkedin = "https://linkedin.com/" },
   # { youtube = "https://youtube.com/" },
#   ]
