languageCode = "fr"
languageName = "French"
displayName = ":flag-fr:"
isoCode = "fr"
weight = 1
rtl = false

title = "Elsa & Antoine"
# logo = "img/logo.jpg"
# description = "23 septembre 2023"
copyright = "&copy; Elsa :heart: Antoine"

dateFormat = "2 January 2006"

[author]
  name = "Elsa & Antoine"
  image = "img/author.jpg"
